--
-- PostgreSQL database dump
--

-- Dumped from database version 12.13 (Ubuntu 12.13-1.pgdg20.04+1)
-- Dumped by pg_dump version 14.4

-- Started on 2022-11-27 14:24:22 MST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: bffhvkybeuoyxl
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO bffhvkybeuoyxl;

--
-- TOC entry 3972 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: bffhvkybeuoyxl
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 203 (class 1259 OID 204026)
-- Name: recipenest_recipes; Type: TABLE; Schema: public; Owner: bffhvkybeuoyxl
--

CREATE TABLE public.recipenest_recipes (
    id integer NOT NULL,
    recipe_name text NOT NULL,
    url text NOT NULL,
    description text,
    notes text,
    img_url text,
    date_created timestamp with time zone DEFAULT now() NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.recipenest_recipes OWNER TO bffhvkybeuoyxl;

--
-- TOC entry 204 (class 1259 OID 204033)
-- Name: recipenest_recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE public.recipenest_recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipenest_recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 204035)
-- Name: recipenest_users; Type: TABLE; Schema: public; Owner: bffhvkybeuoyxl
--

CREATE TABLE public.recipenest_users (
    id integer NOT NULL,
    full_name text NOT NULL,
    user_name text NOT NULL,
    password text NOT NULL,
    nickname text,
    date_created timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.recipenest_users OWNER TO bffhvkybeuoyxl;

--
-- TOC entry 206 (class 1259 OID 204042)
-- Name: recipenest_users_id_seq; Type: SEQUENCE; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE public.recipenest_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipenest_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 204044)
-- Name: schemaversion; Type: TABLE; Schema: public; Owner: bffhvkybeuoyxl
--

CREATE TABLE public.schemaversion (
    version bigint NOT NULL,
    name text,
    md5 text,
    run_at timestamp with time zone
);


ALTER TABLE public.schemaversion OWNER TO bffhvkybeuoyxl;

--
-- TOC entry 3962 (class 0 OID 204026)
-- Dependencies: 203
-- Data for Name: recipenest_recipes; Type: TABLE DATA; Schema: public; Owner: bffhvkybeuoyxl
--

INSERT INTO public.recipenest_recipes VALUES (1, 'Pork Tenderloin', 'https://thebetteredblondie.com/the-best-instant-pot-pork-tenderloin/', NULL, 'Very simple and easy. Instant Pot.', 'https://i2.wp.com/thebetteredblondie.com/wp-content/uploads/2019/06/IMG_0475.jpg?w=1927&ssl=1', '2021-01-30 17:20:56.971446+00', 1);
INSERT INTO public.recipenest_recipes VALUES (2, 'Spinach Cilantro Meatballs', 'https://www.savorylotus.com/spinach-cilantro-meatballs-grain-free/?utm_content=buffer4985f&utm_medium=social&utm_source=pinterest.com&utm_campaign=WNMbuffer', NULL, 'Cook for a few minutes less than the recipe says.', 'https://www.savorylotus.com/wp-content/uploads/2014/03/Spinach-Cilantro-Meatballs.jpeg', '2021-01-30 17:21:35.997176+00', 1);
INSERT INTO public.recipenest_recipes VALUES (5, 'Snickerdoole Cookies', 'https://eatbeautiful.net/paleo-aip-snickerdoodles-egg-free-nut-free/', NULL, 'A yummy treat! Paleo & AIP.', 'https://eatbeautiful.net/wp-content/uploads/2019/04/paleo-aip-snickerdoodles-one-bowl.jpg', '2021-01-30 17:22:42.87458+00', 1);
INSERT INTO public.recipenest_recipes VALUES (10, 'Chipotle Cilantro Lime Rice', 'https://www.skinnytaste.com/chipotle-cilantro-lime-rice-4-pts/', NULL, 'Actually tastes like rice from Chipotles!', 'https://i.pinimg.com/originals/71/fd/79/71fd79ff32acd3aab5821a64c54ea563.jpg', '2021-02-02 22:29:17.063217+00', 1);
INSERT INTO public.recipenest_recipes VALUES (14, 'Fried Chicken', 'https://www.thetasteofkosher.com/fried-chicken-without-buttermilk/', NULL, 'no buttermilk', 'https://www.thetasteofkosher.com/wp-content/uploads/2018/07/Southern_Fried_Chicken.jpg.webp', '2021-02-03 01:14:44.019308+00', 1);
INSERT INTO public.recipenest_recipes VALUES (15, 'test', 'https://google.com', NULL, 'test ntes', 'https://i.pinimg.com/originals/71/fd/79/71fd79ff32acd3aab5821a64c54ea563.jpg', '2021-02-03 01:43:46.779971+00', 3);
INSERT INTO public.recipenest_recipes VALUES (12, 'Awesome Tacos', 'https://www.thewholesomedish.com/the-best-homemade-tacos/', NULL, 'Easy and delicious.', 'https://www.thewholesomedish.com/wp-content/uploads/2019/06/THE-BEST-CLASSIC-TACOS-600X900.jpg', '2021-02-03 01:01:53.680684+00', 1);
INSERT INTO public.recipenest_recipes VALUES (27, 'Test', 'http://test.com', NULL, 'Good jorb.', 'https://i.pinimg.com/originals/71/fd/79/71fd79ff32acd3aab5821a64c54ea563.jpg', '2021-02-04 03:14:50.211942+00', 11);
INSERT INTO public.recipenest_recipes VALUES (3, 'Carrot Cake Muffins', 'https://www.glutenfreepalate.com/carrot-travel-muffins-9-ingredients/', NULL, 'Delicious blend of spices.
Paleo.', 'https://www.glutenfreepalate.com/wp-content/uploads/2014/11/Grain-Free-Carrot-Cake-Muffins1.2.jpg.webp', '2021-01-30 17:21:56.972125+00', 1);


--
-- TOC entry 3964 (class 0 OID 204035)
-- Dependencies: 205
-- Data for Name: recipenest_users; Type: TABLE DATA; Schema: public; Owner: bffhvkybeuoyxl
--

INSERT INTO public.recipenest_users VALUES (1, 'Demo User', 'demo', '$2a$12$d4XXHs9AFVelVxg5YzdjUOfrjivPLW93Pp7Rbu9/IXwEgSHwOHLSi', '', '2021-01-30 17:19:07.069706+00');
INSERT INTO public.recipenest_users VALUES (2, 'jeff', 'jeff', '$2a$12$Ysg4BlD2CkJRSh.LMU1zDuj43h5aOVZ4..ZbzmiaITNUFUEzAoWWm', 'jeff', '2021-01-31 13:28:26.68044+00');
INSERT INTO public.recipenest_users VALUES (3, 'chris sheets', 'csheets', '$2a$12$f7LLbTUAq03owiAFmdtmMOhMJ.WwhZ0cNHTa6RwEXXyilHMMgixJC', '', '2021-02-03 01:42:44.208988+00');
INSERT INTO public.recipenest_users VALUES (4, 'Sam Sheets', 'samsheets', '$2a$12$7iWwCaQ/6Cv0Bic9j.PR5eIgOG458gnBCHyBCm5iJzb/NADR/wA3m', '', '2021-02-03 18:38:24.040034+00');
INSERT INTO public.recipenest_users VALUES (10, 'Test User', 'test', '$2a$12$RLvQ5.SzxASMAV3LVwheHuOte6V6PycWT5rEZ2FRIg1pbFr4MEsfS', '', '2021-02-03 23:55:43.696956+00');
INSERT INTO public.recipenest_users VALUES (11, 'jharris', 'jharris', '$2a$12$shZpznSgGkfQmJzH.H1QPObPg53mVfw9uoem0M2F.TGLjn9PfDmaq', '', '2021-02-04 03:13:55.738307+00');
INSERT INTO public.recipenest_users VALUES (12, 'Testing', 'sunny', '$2a$12$DBRfdPvBMB96aZCpwxQsT.ZZ4qICHBCS.fvW74jAG1eLPR0QfkSRu', '', '2021-03-27 16:34:42.93417+00');


--
-- TOC entry 3966 (class 0 OID 204044)
-- Dependencies: 207
-- Data for Name: schemaversion; Type: TABLE DATA; Schema: public; Owner: bffhvkybeuoyxl
--

INSERT INTO public.schemaversion VALUES (0, NULL, NULL, NULL);
INSERT INTO public.schemaversion VALUES (1, 'create_recipenest_users', '43d8d0bd4ce00f970b768d2ba375cb5a', '2021-01-30 17:06:05.652+00');
INSERT INTO public.schemaversion VALUES (2, 'create_recipenest_recipes', 'c9800fc23486b62e629a9873e8c79978', '2021-01-30 17:06:05.671+00');


--
-- TOC entry 3975 (class 0 OID 0)
-- Dependencies: 204
-- Name: recipenest_recipes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bffhvkybeuoyxl
--

SELECT pg_catalog.setval('public.recipenest_recipes_id_seq', 32, true);


--
-- TOC entry 3976 (class 0 OID 0)
-- Dependencies: 206
-- Name: recipenest_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bffhvkybeuoyxl
--

SELECT pg_catalog.setval('public.recipenest_users_id_seq', 12, true);


--
-- TOC entry 3828 (class 2606 OID 204051)
-- Name: recipenest_recipes recipenest_recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE ONLY public.recipenest_recipes
    ADD CONSTRAINT recipenest_recipes_pkey PRIMARY KEY (id);


--
-- TOC entry 3830 (class 2606 OID 204053)
-- Name: recipenest_users recipenest_users_pkey; Type: CONSTRAINT; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE ONLY public.recipenest_users
    ADD CONSTRAINT recipenest_users_pkey PRIMARY KEY (id);


--
-- TOC entry 3832 (class 2606 OID 204055)
-- Name: recipenest_users recipenest_users_user_name_key; Type: CONSTRAINT; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE ONLY public.recipenest_users
    ADD CONSTRAINT recipenest_users_user_name_key UNIQUE (user_name);


--
-- TOC entry 3834 (class 2606 OID 204057)
-- Name: schemaversion schemaversion_pkey; Type: CONSTRAINT; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE ONLY public.schemaversion
    ADD CONSTRAINT schemaversion_pkey PRIMARY KEY (version);


--
-- TOC entry 3835 (class 2606 OID 204058)
-- Name: recipenest_recipes recipenest_recipes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: bffhvkybeuoyxl
--

ALTER TABLE ONLY public.recipenest_recipes
    ADD CONSTRAINT recipenest_recipes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.recipenest_users(id) ON DELETE CASCADE;


--
-- TOC entry 3973 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: bffhvkybeuoyxl
--

REVOKE ALL ON SCHEMA public FROM postgres;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO bffhvkybeuoyxl;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- TOC entry 3974 (class 0 OID 0)
-- Dependencies: 640
-- Name: LANGUAGE plpgsql; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON LANGUAGE plpgsql TO bffhvkybeuoyxl;


-- Completed on 2022-11-27 14:24:28 MST

--
-- PostgreSQL database dump complete
--

