CREATE TABLE recipenest_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    nickname TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);