CREATE TABLE recipenest_recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_name TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    notes TEXT,
    img_url TEXT,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id INTEGER REFERENCES recipenest_users(id) ON DELETE CASCADE NOT NULL
);